### ISSUE TITLE
Logos are missing

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythiaCookbooks/mpl-colorbar-cookbook#10]
On this page: https://cookbooks.projectpythia.org/mpl-colorbar-cookbook/notebooks/mpl-colorbar-cookbook.html
the logos seem to be missing!

**Comment by brian-rose** [comment]
JupyterBook has some idiosyncrasies about how images are treated during the book build: https://jupyterbook.org/en/stable/content/figures.html

**Comment by hCraker** [comment]
Thanks for bringing this to my attention. Using markdown instead of embedded HTML should fix it. I'll get working on it now
