### ISSUE TITLE
Move _config.yaml

### ISSUE THREAD

**Issue by jukent** [ProjectPythiaCookbooks/mpl-colorbar-cookbook#3]
@hCraker Can you move your `_config.yaml` up one level so that it matches the notebook template? I need this to be consistent across repositories able to auto grab information from the config file for the gallery.

**Comment by hCraker** [comment]
I'm not sure why, but I cannot push to this repository now that I've transferred ownership to ProjectPythiaCookbooks. @jukent can you help me with this?

**Comment by jukent** [comment]
@hCraker Can you still make a PR?

**Comment by hCraker** [comment]
@jukent Yes I can make a PR, but I'm having authentication issues when trying to new changes to my branch.

**Comment by jukent** [comment]
It doesn't look like your fork is linked to this upstream main branch anymore?
https://github.com/ProjectPythiaCookbooks/mpl-colorbar-cookbook/network/members

**Comment by hCraker** [comment]
I had to make a fork and change my upstream repo. So now I can push to my fork and then make PRs from there.

**Comment by hCraker** [comment]
I just got this to work!
